// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DailyTypingStat {
    "date": string;
    "count": number;
}

export interface DashboardStats {
    "totalExpansions": number;
    "todayExpansions": number;
    "snippetCount": number;
    "enabledCount": number;
    "todayTypingCount": number;
    "averageDailyTyping": number;
    "typingHistory": DailyTypingStat[] | null;
    "topSnippets": Snippet[] | null;
}

export interface Label {
    "id": number;
    "name": string;
    "description": string;
    "color": string;
    "snippetCount": number;
    "enabledCount": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface LabelInput {
    "name": string;
    "description": string;
    "color": string;
}

export interface Snippet {
    "id": number;
    "labelId": number;
    "shortcut": string;
    "title": string;
    "content": string;
    "contentType": string;
    "enabled": boolean;
    "caseSensitive": boolean;
    "usePaste": boolean;
    "expandMode": string;
    "usageCount": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface SnippetInput {
    "labelId": number;
    "shortcut": string;
    "title": string;
    "content": string;
    "contentType": string;
    "enabled": boolean;
    "caseSensitive": boolean;
    "usePaste": boolean;
    "expandMode": string;
}
