// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "./internal/platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./internal/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActivateProcess(processID: number): $CancellablePromise<void> {
    return $Call.ByID(4248908197, processID);
}

export function AssignSnippetLabel(snippetID: number, labelID: number): $CancellablePromise<storage$0.Snippet> {
    return $Call.ByID(289982225, snippetID, labelID);
}

export function BrowseAIPromptApp(): $CancellablePromise<platform$0.AppInfo> {
    return $Call.ByID(4178716338);
}

export function CancelAIRequest(): $CancellablePromise<void> {
    return $Call.ByID(154486394);
}

export function CancelTTSModelDownload(): $CancellablePromise<void> {
    return $Call.ByID(1270262625);
}

export function ConfirmLabelDeletion(name: string): $CancellablePromise<boolean> {
    return $Call.ByID(2768525009, name);
}

export function ConfirmSnippetDeletion(title: string): $CancellablePromise<boolean> {
    return $Call.ByID(3509352734, title);
}

export function CreateAIPromptProfile(input: $models.AIPromptProfileInput): $CancellablePromise<$models.AIPromptSettings> {
    return $Call.ByID(1682044222, input);
}

export function CreateLabel(input: storage$0.LabelInput): $CancellablePromise<storage$0.Label> {
    return $Call.ByID(1306064861, input);
}

export function CreateSnippet(input: storage$0.SnippetInput): $CancellablePromise<storage$0.Snippet> {
    return $Call.ByID(1839557182, input);
}

export function DeleteAIPromptProfile(id: string): $CancellablePromise<$models.AIPromptSettings> {
    return $Call.ByID(658405355, id);
}

export function DeleteLabel(id: number): $CancellablePromise<void> {
    return $Call.ByID(102558456, id);
}

export function DeleteSnippet(id: number): $CancellablePromise<void> {
    return $Call.ByID(4243157291, id);
}

export function GetAIPromptSettings(): $CancellablePromise<$models.AIPromptSettings> {
    return $Call.ByID(3364574746);
}

export function GetAISettings(): $CancellablePromise<ai$0.Settings> {
    return $Call.ByID(84577668);
}

export function GetDashboard(): $CancellablePromise<storage$0.DashboardStats> {
    return $Call.ByID(164996217);
}

export function GetGeneralSettings(): $CancellablePromise<$models.GeneralSettings> {
    return $Call.ByID(3269573032);
}

export function GetPlatformStatus(): $CancellablePromise<platform$0.Status> {
    return $Call.ByID(2605037362);
}

export function GetTTSModelStatus(): $CancellablePromise<ai$0.TTSModelStatus> {
    return $Call.ByID(1521521987);
}

export function ListLabels(): $CancellablePromise<storage$0.Label[] | null> {
    return $Call.ByID(1658064502);
}

export function ListSnippets(query: string): $CancellablePromise<storage$0.Snippet[] | null> {
    return $Call.ByID(3548108915, query);
}

export function ListSnippetsByLabel(query: string, labelID: number): $CancellablePromise<storage$0.Snippet[] | null> {
    return $Call.ByID(161922596, query, labelID);
}

export function LogExpansion(snippetID: number, appBundleID: string): $CancellablePromise<void> {
    return $Call.ByID(56754110, snippetID, appBundleID);
}

export function MakeAIRequest(endpoint: string, headers: { [_ in string]?: string } | null, body: string): $CancellablePromise<string> {
    return $Call.ByID(437593542, endpoint, headers, body);
}

export function ReplaceSelectedText(processID: number, replacement: string): $CancellablePromise<void> {
    return $Call.ByID(372690625, processID, replacement);
}

export function RequestAccessibilityPermission(): $CancellablePromise<platform$0.Status> {
    return $Call.ByID(1098525461);
}

export function RunAIAssist(input: ai$0.AssistRequest): $CancellablePromise<ai$0.AssistResult> {
    return $Call.ByID(2229821831, input);
}

export function SaveAISettings(settings: ai$0.Settings): $CancellablePromise<ai$0.Settings> {
    return $Call.ByID(1999356331, settings);
}

export function SaveCommonAIPromptRule(rule: $models.AIPromptRule): $CancellablePromise<$models.AIPromptSettings> {
    return $Call.ByID(691108791, rule);
}

export function SaveGeneralSettings(settings: $models.GeneralSettings): $CancellablePromise<$models.GeneralSettings> {
    return $Call.ByID(4277102661, settings);
}

export function SetLabelSnippetsEnabled(labelID: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2389042794, labelID, enabled);
}

export function Speak(text: string): $CancellablePromise<void> {
    return $Call.ByID(1892369553, text);
}

export function StartTTSModelDownload(): $CancellablePromise<void> {
    return $Call.ByID(1241213861);
}

export function StopSpeaking(): $CancellablePromise<void> {
    return $Call.ByID(3590611999);
}

export function TestSpeak(text: string, settings: ai$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1255303217, text, settings);
}

export function ToggleSnippet(id: number, enabled: boolean): $CancellablePromise<storage$0.Snippet> {
    return $Call.ByID(3992326870, id, enabled);
}

export function UpdateAIPromptProfile(id: string, input: $models.AIPromptProfileInput): $CancellablePromise<$models.AIPromptSettings> {
    return $Call.ByID(2547313181, id, input);
}

export function UpdateLabel(id: number, input: storage$0.LabelInput): $CancellablePromise<storage$0.Label> {
    return $Call.ByID(3509773802, id, input);
}

export function UpdateSnippet(id: number, input: storage$0.SnippetInput): $CancellablePromise<storage$0.Snippet> {
    return $Call.ByID(3595804081, id, input);
}
