// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AIPromptProfile {
    "id": string;
    "appName": string;
    "appBundleId": string;
    "useSelectedText": boolean;
    "runWithoutSelection": boolean;
    "selectedTextPrompt": string;
    "noSelectionPrompt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface AIPromptProfileInput {
    "appName": string;
    "appBundleId": string;
    "useSelectedText": boolean;
    "runWithoutSelection": boolean;
    "selectedTextPrompt": string;
    "noSelectionPrompt": string;
}

export interface AIPromptRule {
    "useSelectedText": boolean;
    "runWithoutSelection": boolean;
    "selectedTextPrompt": string;
    "noSelectionPrompt": string;
}

export interface AIPromptSettings {
    "common": AIPromptRule;
    "profiles": AIPromptProfile[] | null;
}

export interface GeneralSettings {
    "themeMode": string;
    "language": string;
    "typingTrendEnabled": boolean;
    "startAtLogin": boolean;
    "soundName": string;
}
