// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppleIntelligenceStatus {
    "available": boolean;
    "state": string;
    "detail"?: string;
}

export interface AssistRequest {
    "instruction": string;
    "contextKind": ContextKind;
    "contextText": string;
    "filePath": string;
    "appName": string;
    "appBundleId": string;
    "customPrompt": string;
}

export interface AssistResult {
    "intent": string;
    "supportReport": string;
    "replacement": string;
}

export enum ContextKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextNone = "none",
    ContextSelectedText = "selected_text",
    ContextSelectedFile = "selected_file",
};

export interface Settings {
    "enabled": boolean;
    "provider": string;
    "endpoint": string;
    "model": string;
    "apiKey": string;
    "temperature": number;
    "hotkey": string;
    "useSelectedText": boolean;
    "useSelectedFile": boolean;
    "replaceSelectedText": boolean;
    "pasteReplacementBundleIds": string[] | null;

    /**
     * TTS Settings
     */
    "ttsEnabled": boolean;

    /**
     * "os" or "supertonic3"
     */
    "ttsEngine": string;

    /**
     * e.g., "http://localhost:7788"
     */
    "ttsEndpoint": string;

    /**
     * e.g., "default" or "M1", "F1", etc.
     */
    "ttsVoice": string;

    /**
     * Speak on AI response
     */
    "ttsUseAiResponse": boolean;

    /**
     * Speak on shortcut hotkey
     */
    "ttsUseShortcut": boolean;

    /**
     * Hotkey for TTS reading
     */
    "ttsShortcut": string;

    /**
     * Speech speed factor (0.7 - 2.0)
     */
    "ttsSpeed": number;

    /**
     * Number of denoising steps (5 - 12)
     */
    "ttsSteps": number;
}

/**
 * TTSModelStatus holds status for downloading models
 */
export interface TTSModelStatus {
    "isDownloaded": boolean;

    /**
     * "idle", "downloading", "done", "error"
     */
    "status": string;
    "progress": number;
    "currentFile": string;
    "error"?: string;
}
