// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {platform} from '../models';
import {main} from '../models';
import {ai} from '../models';

export function ActivateProcess(arg1:number):Promise<void>;

export function AssignSnippetLabel(arg1:number,arg2:number):Promise<storage.Snippet>;

export function BrowseAIPromptApp():Promise<platform.AppInfo>;

export function CancelAIRequest():Promise<void>;

export function ConfirmLabelDeletion(arg1:string):Promise<boolean>;

export function ConfirmSnippetDeletion(arg1:string):Promise<boolean>;

export function CreateAIPromptProfile(arg1:main.AIPromptProfileInput):Promise<main.AIPromptSettings>;

export function CreateLabel(arg1:storage.LabelInput):Promise<storage.Label>;

export function CreateSnippet(arg1:storage.SnippetInput):Promise<storage.Snippet>;

export function DeleteAIPromptProfile(arg1:string):Promise<main.AIPromptSettings>;

export function DeleteLabel(arg1:number):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function GetAIPromptSettings():Promise<main.AIPromptSettings>;

export function GetAISettings():Promise<ai.Settings>;

export function GetDashboard():Promise<storage.DashboardStats>;

export function GetGeneralSettings():Promise<main.GeneralSettings>;

export function GetPlatformStatus():Promise<platform.Status>;

export function ListLabels():Promise<Array<storage.Label>>;

export function ListSnippets(arg1:string):Promise<Array<storage.Snippet>>;

export function ListSnippetsByLabel(arg1:string,arg2:number):Promise<Array<storage.Snippet>>;

export function LogExpansion(arg1:number,arg2:string):Promise<void>;

export function MakeAIRequest(arg1:string,arg2:Record<string, string>,arg3:string):Promise<string>;

export function ReplaceSelectedText(arg1:number,arg2:string):Promise<void>;

export function RequestAccessibilityPermission():Promise<platform.Status>;

export function RunAIAssist(arg1:ai.AssistRequest):Promise<ai.AssistResult>;

export function SaveAISettings(arg1:ai.Settings):Promise<ai.Settings>;

export function SaveCommonAIPromptRule(arg1:main.AIPromptRule):Promise<main.AIPromptSettings>;

export function SaveGeneralSettings(arg1:main.GeneralSettings):Promise<main.GeneralSettings>;

export function SetLabelSnippetsEnabled(arg1:number,arg2:boolean):Promise<void>;

export function ToggleSnippet(arg1:number,arg2:boolean):Promise<storage.Snippet>;

export function UpdateAIPromptProfile(arg1:string,arg2:main.AIPromptProfileInput):Promise<main.AIPromptSettings>;

export function UpdateLabel(arg1:number,arg2:storage.LabelInput):Promise<storage.Label>;

export function UpdateSnippet(arg1:number,arg2:storage.SnippetInput):Promise<storage.Snippet>;
