// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProcess(arg1) {
  return window['go']['main']['App']['ActivateProcess'](arg1);
}

export function AssignSnippetLabel(arg1, arg2) {
  return window['go']['main']['App']['AssignSnippetLabel'](arg1, arg2);
}

export function BrowseAIPromptApp() {
  return window['go']['main']['App']['BrowseAIPromptApp']();
}

export function CancelAIRequest() {
  return window['go']['main']['App']['CancelAIRequest']();
}

export function ConfirmLabelDeletion(arg1) {
  return window['go']['main']['App']['ConfirmLabelDeletion'](arg1);
}

export function ConfirmSnippetDeletion(arg1) {
  return window['go']['main']['App']['ConfirmSnippetDeletion'](arg1);
}

export function CreateAIPromptProfile(arg1) {
  return window['go']['main']['App']['CreateAIPromptProfile'](arg1);
}

export function CreateLabel(arg1) {
  return window['go']['main']['App']['CreateLabel'](arg1);
}

export function CreateSnippet(arg1) {
  return window['go']['main']['App']['CreateSnippet'](arg1);
}

export function DeleteAIPromptProfile(arg1) {
  return window['go']['main']['App']['DeleteAIPromptProfile'](arg1);
}

export function DeleteLabel(arg1) {
  return window['go']['main']['App']['DeleteLabel'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function GetAIPromptSettings() {
  return window['go']['main']['App']['GetAIPromptSettings']();
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetGeneralSettings() {
  return window['go']['main']['App']['GetGeneralSettings']();
}

export function GetPlatformStatus() {
  return window['go']['main']['App']['GetPlatformStatus']();
}

export function ListLabels() {
  return window['go']['main']['App']['ListLabels']();
}

export function ListSnippets(arg1) {
  return window['go']['main']['App']['ListSnippets'](arg1);
}

export function ListSnippetsByLabel(arg1, arg2) {
  return window['go']['main']['App']['ListSnippetsByLabel'](arg1, arg2);
}

export function LogExpansion(arg1, arg2) {
  return window['go']['main']['App']['LogExpansion'](arg1, arg2);
}

export function MakeAIRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeAIRequest'](arg1, arg2, arg3);
}

export function ReplaceSelectedText(arg1, arg2) {
  return window['go']['main']['App']['ReplaceSelectedText'](arg1, arg2);
}

export function RequestAccessibilityPermission() {
  return window['go']['main']['App']['RequestAccessibilityPermission']();
}

export function RunAIAssist(arg1) {
  return window['go']['main']['App']['RunAIAssist'](arg1);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveCommonAIPromptRule(arg1) {
  return window['go']['main']['App']['SaveCommonAIPromptRule'](arg1);
}

export function SaveGeneralSettings(arg1) {
  return window['go']['main']['App']['SaveGeneralSettings'](arg1);
}

export function SetLabelSnippetsEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetLabelSnippetsEnabled'](arg1, arg2);
}

export function ToggleSnippet(arg1, arg2) {
  return window['go']['main']['App']['ToggleSnippet'](arg1, arg2);
}

export function UpdateAIPromptProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateAIPromptProfile'](arg1, arg2);
}

export function UpdateLabel(arg1, arg2) {
  return window['go']['main']['App']['UpdateLabel'](arg1, arg2);
}

export function UpdateSnippet(arg1, arg2) {
  return window['go']['main']['App']['UpdateSnippet'](arg1, arg2);
}
