// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppInfo {
    "name": string;
    "bundleId": string;
    "path": string;
}

export interface Status {
    "accessibilityTrusted": boolean;
    "secureInputActive": boolean;
    "activeAppName": string;
    "activeBundleId": string;
    "flowEngineRunning": boolean;
    "flowPaused": boolean;
    "message": string;
}
